### ISSUE TITLE
sliding problem

### ISSUE THREAD

**Issue by ZhiangChen** [DREAMS-lab/pbr_gazebo#1]
The "rocks" have a sliding problem, and the friction does not work. The problem is also posted on Gazebosim.org: https://answers.gazebosim.org/question/25964/sliding-problem-friction-does-not-work/

**Comment by darknight-007** [comment]
Interesting, I did a quick read. Seems they can't deal with transition from stiction to friction? Let me read more. Good stuff.

**Comment by ZhiangChen** [comment]
This problem is caused by ODE. It can't solve the physics properly when a surface has a small friction coefficient. I solved this problem by changing to Bullet engine.
